"""
Industry Challenges Models

Real-world challenges covering:
- System Design Problems
- Scalability Challenges  
- Algorithm Optimization
- Software Architecture Problems
"""

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Enum, Boolean, JSON, Float
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import enum
from app.database import Base


class ChallengeCategory(str, enum.Enum):
    SYSTEM_DESIGN = "system_design"
    SCALABILITY = "scalability"
    ALGORITHM_OPTIMIZATION = "algorithm_optimization"
    SOFTWARE_ARCHITECTURE = "software_architecture"


class ChallengeDifficulty(str, enum.Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"
    EXPERT = "expert"


class SolutionStatus(str, enum.Enum):
    DRAFT = "draft"
    SUBMITTED = "submitted"
    UNDER_REVIEW = "under_review"
    EVALUATED = "evaluated"
    RESUME_WORTHY = "resume_worthy"


class IndustryChallenge(Base):
    """
    Stores real-world industry challenges generated by AI
    """
    __tablename__ = "industry_challenges"

    id = Column(Integer, primary_key=True, index=True)
    
    # Challenge metadata
    title = Column(String(255), nullable=False)
    category = Column(Enum(ChallengeCategory), nullable=False)
    difficulty = Column(Enum(ChallengeDifficulty), nullable=False)
    
    # Challenge content
    problem_statement = Column(Text, nullable=False)
    context = Column(Text, nullable=False)  # Industry context/background
    constraints = Column(JSON, nullable=False)  # Technical constraints
    requirements = Column(JSON, nullable=False)  # Functional requirements
    
    # Evaluation criteria
    evaluation_criteria = Column(JSON, nullable=False)
    expected_concepts = Column(JSON, nullable=False)  # Concepts solution should cover
    
    # Industry tags
    industry = Column(String(100))  # e.g., "E-commerce", "FinTech", "Healthcare"
    company_type = Column(String(100))  # e.g., "Startup", "Enterprise", "FAANG"
    tech_stack_hints = Column(JSON)  # Suggested technologies
    
    # Metadata
    estimated_time_hours = Column(Float, default=2.0)
    xp_reward = Column(Integer, default=500)
    is_active = Column(Boolean, default=True)
    times_attempted = Column(Integer, default=0)
    success_rate = Column(Float, default=0.0)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    solutions = relationship("ChallengeSolution", back_populates="challenge")


class ChallengeSolution(Base):
    """
    User-submitted solutions to industry challenges
    """
    __tablename__ = "challenge_solutions"

    id = Column(Integer, primary_key=True, index=True)
    
    # Foreign keys
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    challenge_id = Column(Integer, ForeignKey("industry_challenges.id"), nullable=False)
    
    # Solution content
    solution_text = Column(Text, nullable=False)
    architecture_diagram = Column(Text)  # Mermaid/ASCII diagram
    trade_offs_discussed = Column(JSON)  # Trade-offs identified
    technologies_proposed = Column(JSON)  # Tech stack choices
    
    # AI Evaluation
    status = Column(Enum(SolutionStatus), default=SolutionStatus.DRAFT)
    ai_feedback = Column(Text)
    strengths = Column(JSON)  # Strong points identified
    areas_for_improvement = Column(JSON)
    innovation_score = Column(Float)  # 0-100 innovation rating
    practicality_score = Column(Float)  # 0-100 practicality rating
    completeness_score = Column(Float)  # 0-100 completeness rating
    overall_score = Column(Float)  # Weighted average
    
    # Resume recommendation
    is_resume_worthy = Column(Boolean, default=False)
    resume_bullet_points = Column(JSON)  # Suggested resume lines
    resume_recommendation_reason = Column(Text)
    
    # Timestamps
    submitted_at = Column(DateTime(timezone=True))
    evaluated_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # XP awarded
    xp_earned = Column(Integer, default=0)
    
    # Relationships
    challenge = relationship("IndustryChallenge", back_populates="solutions")
    user = relationship("User", backref="challenge_solutions")


class ResumeHighlight(Base):
    """
    Stores resume-worthy achievements from challenges
    """
    __tablename__ = "resume_highlights"

    id = Column(Integer, primary_key=True, index=True)
    
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    solution_id = Column(Integer, ForeignKey("challenge_solutions.id"), nullable=False)
    
    # Resume content
    headline = Column(String(255), nullable=False)
    bullet_points = Column(JSON, nullable=False)
    skills_demonstrated = Column(JSON, nullable=False)
    impact_statement = Column(Text)
    
    # User actions
    added_to_resume = Column(Boolean, default=False)
    exported_at = Column(DateTime(timezone=True))
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    solution = relationship("ChallengeSolution", backref="resume_highlight")
    user = relationship("User", backref="resume_highlights")
